### PR TITLE
Don't use symmetric comparison between branches

### PR DESCRIPTION
**Pull request by ghunti**
Hi, thanks for your plugin. I'm trying to use it, but I was having a hard time since the plugin was only identifying 2 or 3 commits of difference between two branches while it should have found around 80.
Digging the code, and also the `simple-git` plugin code, I've found that by not passing anything in the `opts.symmetric` option we are actually getting the commits present on each branch that are not present on both branches. Everything works if the branches have the same commit history, and only one of the branches has extra commits. If both branches have different commit histories, then when we try to build the logs from the graph something goes really wrong and my 80 commits are reduced to 3.

I really think that we don't want to use the symmetric comparison. More info here https://stackoverflow.com/questions/462974/what-are-the-differences-between-double-dot-and-triple-dot-in-git-com

Thanks

### CODE REVIEW

**Comment by ghunti** [comment]
@jgillick  ping :-)

**Comment by jgillick** [comment]
I will take a look at your PR this week. Thank you for the submission!

**Comment by jgillick** [comment]
Looks good, tested locally and works. Thank you for your contribution. This will go into version 1.6.1 today.

**Comment by jgillick** [comment]
Published!

**Comment by ghunti** [comment]
Thanks!

**Comment by jgillick** [comment]
FYI @ghunti, I just released a new version (v2.0.0) that makes `symmetric` configurable due to a bug related to the git range parsing. This shouldn't break your implementation, but please try it and let me know. (I no longer work somewhere that uses Jira, so my ability to test outside of unit tests are limited, currently)

**Pull request merged**
