### PR TITLE
fixed parseRange bug with string split

### PR DESCRIPTION
**Pull request by ndecapite**
There is an error when the versions have a . in them. I fixed this and am working on a one line fix as I write this.

### CODE REVIEW

**Comment by jgillick** [comment]
Awesome. Thanks for the contribution. I don't think a one-liner is completely necessary (otherwise we end up with an even more complex regex: `/(.+?)((\.{2,3})(.*))?$/`). But perhaps refactor the code a bit like this (I have not tested this):

```js
let parts = [];
let symmetric = false;

if (rangeStr.includes('...')) {
  symmetric = true;
  parts = rangeStr.split('...');
} else if (rangeStr.includes('..')){
  parts = rangeStr.split('..');
} else if (rangeStr.length > 0){
  parts[0] = rangeStr;
}

if (!parts.length) {
    throw new Error('Invalid Range');
}

return {
    symmetric,
    from: parts[0],
    to: parts[1] || '',
}
```

Also, please add a test case to `cli.test.js` and remove the `.idea` directory that your IDE added.

Thanks again!

**Comment by ndecapite** [comment]
Hey I just added your code with a minor tweak (the use case when its just '...' or '..' inputted). I also should have removed the .idea folder with my git ignore commit.

**Comment by mrmeyers99** [comment]
This is to fix https://github.com/jgillick/jira-changelog/issues/27

**Comment by ndecapite** [comment]
Anything left for me to do? Would really help out our team once this is in master!

**Comment by jgillick** [comment]
Looks great. Thank you for your contribution!

**Comment by jgillick** [comment]
Your update has been deployed to version 2.2.0.

**Pull request merged**
